[package]
name = "aoike-sycamore"
version = "0.1.0"
authors = ["AzurIce <973562770@qq.com>"]
edition = "2021"

[features]
build = ["aoike/build", "dep:zip"]

[dependencies]
aoike.workspace = true
sycamore = { version = "0.9", features = ["web"] }
sycamore-router = "0.9"
time = { version = "0.3.43", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"

zip = { version = "5.1.1", optional = true }

[build-dependencies]
zip = "5.1.1"
anyhow = "1.0.100"
walkdir = "2.5.0"