[package]
name = "aoike-sycamore"
version = "0.1.0"
authors = ["AzurIce <973562770@qq.com>"]
edition = "2021"

[features]
build = ["aoike/build", "dep:include_dir"]

[dependencies]
aoike.workspace = true
sycamore = { version = "0.9", features = ["web"] }
sycamore-router = "0.9"
time = { version = "0.3.43", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"

include_dir = { version = "0.7.4", optional = true }
