[package]
name = "aoike-sycamore"
version = "0.1.0"
authors = ["AzurIce <973562770@qq.com>"]
edition = "2021"

[dependencies]
aoike.workspace = true
sycamore = { version = "0.9", features = ["web"] }
sycamore-router = "0.9"
time = { version = "0.3.43", features = ["wasm-bindgen"] }
web-sys = { version = "0.3", features = ["Window", "Document", "HtmlScriptElement", "Node"] }
wasm-bindgen = "0.2"
