[package]
name = "aoike-sycamore"
version = "0.1.0"
authors = ["AzurIce <973562770@qq.com>"]
edition = "2024"

[features]
build = ["aoike/build", "dep:zip"]

[dependencies]
aoike.workspace = true
sycamore = { version = "0.9", features = ["web"] }
sycamore-router = "0.9"
time = { version = "0.3.43", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"

zip = { version = "6.0.0", optional = true }
sha1 = "0.10.6"

[build-dependencies]
zip = "6.0.0"
anyhow = "1.0.100"
walkdir = "2.5.0"
sha1 = "0.10"