[package]
name = "example-sycamore"
version = "0.1.0"
authors = ["AzurIce <973562770@qq.com>"]
edition = "2024"
publish = false

[dependencies]
aoike.workspace = true
aoike-sycamore.workspace = true
sycamore = { version = "0.9.2", features = ["web"] }
sycamore-router = "0.9.2"
console_error_panic_hook = "0.1"

[build-dependencies]
aoike = { workspace = true, features = ["build"] }
aoike-sycamore = { workspace = true, features = ["build"] }
walkdir = "2.5.0"
relative-path = "2.0.1"